<?php

namespace AppBundle\Repository;

/**
 * ImeiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImeiRepository extends \Doctrine\ORM\EntityRepository
{
}
