<?php

namespace AppBundle\Repository;

/**
 * masterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class masterRepository extends \Doctrine\ORM\EntityRepository
{
}
