<?php

namespace AppBundle\Repository;

/**
 * PalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalletRepository extends \Doctrine\ORM\EntityRepository
{
}
