<?php

namespace AppBundle\Repository;

/**
 * TransferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
