<?php

namespace AppBundle\Repository;

/**
 * TransporterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporterRepository extends \Doctrine\ORM\EntityRepository
{
}
