<?php

namespace AppBundle\Repository;

/**
 * Warehouse_limitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Warehouse_limitsRepository extends \Doctrine\ORM\EntityRepository
{
}
